/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.uem.iss.petshop.Commons.view;

import br.com.uem.iss.petshop.Interfaces.ControllerListInterface;
import br.com.uem.iss.petshop.Interfaces.ModelListInterface;
import br.com.uem.iss.petshop.Interfaces.ObservableModel;
import br.com.uem.iss.petshop.Interfaces.ObserverModel;
import br.com.uem.iss.petshop.Interfaces.PetshopEntity;
import br.com.uem.iss.petshop.Utils.State;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/**
 *
 * @author Lucas
 */
public class PetshopListConsultView extends javax.swing.JDialog implements ObserverModel{

    /**
     * Creates new form PetshopListConsultView
     */
    final private ModelListInterface listModel;
    final private ControllerListInterface controllerList;
    State state;
    public PetshopListConsultView(java.awt.Frame parent, boolean modal,
            ControllerListInterface c,
            ModelListInterface l) {

        super(parent, modal);
        initComponents();
                listModel = l;
        controllerList = c;
        state = State.STATE_CANCEL;
        ((ObservableModel)listModel).registerErrorObserver(this);
        ((ObservableModel)listModel).registerUpdate(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCustomerTable = new javax.swing.JTable();
        jButtonCancel = new javax.swing.JButton();
        jButtonVisualize = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableCustomerTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButtonCancel.setText("Cancelar");
        jButtonCancel.setFocusable(false);
        jButtonCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButtonVisualize.setText("Visualizar");
        jButtonVisualize.setFocusable(false);
        jButtonVisualize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonVisualize.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonVisualize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonVisualize)
                    .addComponent(jButtonCancel))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonVisualize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVisualizeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonVisualize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCustomerTable;
    // End of variables declaration//GEN-END:variables

    public State getState(){
        return state;
    }
    
    public PetshopEntity configure(AbstractTableModel tableModel) {
        createActions();
        return execControllerInterface(tableModel,jTableCustomerTable);
    }

    public PetshopEntity execControllerInterface(AbstractTableModel tableModel, JTable jTableCustomerTable){
        PetshopEntity entity = null;
        if (tableModel.getRowCount() != 0) {
            jTableCustomerTable.setModel(tableModel);
            setLocationRelativeTo(null);
            setVisible(true);
            if (getState() == State.STATE_CANCEL)
                return null;
            if (getState() == State.STATE_EDIT){
                int value = jTableCustomerTable.getSelectedRow();
                entity = listModel.getPetshopEntityAt(value);
            }
        } else
            state = State.STATE_CANCEL;
        
        return entity;
    }
    
    
    @Override
    public void updateViews(String msg) {
        JOptionPane.showMessageDialog(this, msg);
        jTableCustomerTable.repaint();
    }

    @Override
    public void errorOcurred(String error) {
        JOptionPane.showMessageDialog(this, error);
    }
    
    public void createActions(){
        createVisualizeAction();
        createCancelAction();
    }

    private void createVisualizeAction() {
        jButtonVisualize.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                visualizeAction();
            }
        });
    }

    private void visualizeAction(){
        if (jTableCustomerTable.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this, "Nenhum item selecionado");
            return;
        }
        state = State.STATE_EDIT;
        dispose();
    }
    
    private void createCancelAction() {
        state = State.STATE_CANCEL;
        dispose();
    }

}
