/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.uem.iss.petshop.Login.view;

import br.com.uem.iss.petshop.Interfaces.ObserverJInternalFrame;
import br.com.uem.iss.petshop.Interfaces.ViewInterface;
import br.com.uem.iss.petshop.Login.controller.LoginController;
import br.com.uem.iss.petshop.Login.model.LoginModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ricardo Andrade
 */
public class LoginView extends javax.swing.JInternalFrame implements ViewInterface {

    LoginController loginControler;
    LoginModel loginModel;

    ArrayList<ObserverJInternalFrame> observerJInternalFrames;

    public LoginView(LoginController c, LoginModel m) {
        initComponents();
        loginControler = c;
        loginModel = m;
        observerJInternalFrames = new ArrayList<>();
        updateViewFromModel();
        loginModel.registerErrorObserver(this);
        loginModel.registerUpdate(this);
    }
    /**
     * Creates new form LoginView
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextFieldCodigo = new javax.swing.JTextField();
        jFormattedTextFieldName = new javax.swing.JTextField();
        jFormattedTextFieldLogin = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jButtonCancel = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();

        setTitle("Cadastro de Login");

        jLabel1.setText("Cód.:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Login:");

        jLabel4.setText("Senha:");

        jFormattedTextFieldCodigo.setEditable(false);
        jFormattedTextFieldCodigo.setText("jTextField1");

        jFormattedTextFieldName.setText("jTextField2");

        jFormattedTextFieldLogin.setText("jTextField3");

        jPasswordFieldSenha.setText("jPasswordField1");

        jButtonCancel.setText("Cancelar");

        jButtonRecord.setText("Gravar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonRecord)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jFormattedTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jFormattedTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRecord))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JTextField jFormattedTextFieldCodigo;
    private javax.swing.JTextField jFormattedTextFieldLogin;
    private javax.swing.JTextField jFormattedTextFieldName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    // End of variables declaration//GEN-END:variables
@Override
    public void updateViewFromModel() {
        if (loginModel != null && loginModel.getLogin() != null) {
            jFormattedTextFieldCodigo.setText("0");
            jFormattedTextFieldName.setText(loginModel.getName().toString());
            jFormattedTextFieldLogin.setText(loginModel.getLogin().toString());
            jPasswordFieldSenha.setText(loginModel.getSenha().toString());
        } else {
            jFormattedTextFieldCodigo.setText("0");
            jFormattedTextFieldName.setText(loginModel.getName().toString());
            jFormattedTextFieldLogin.setText(loginModel.getLogin().toString());
            jPasswordFieldSenha.setText(loginModel.getSenha().toString());
        }
    }

    private void finalizeLoginView() {
        updateObserversWasFinalized();
        dispose();
    }

    private void record() {
        loginControler.persist();
        finalizeLoginView();
    }

    private void createActionCancel() {
        jButtonCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                finalizeLoginView();
            }

        });
    }

    private void createActionRecord() {
        jButtonRecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                record();
            }
        });
    }

    @Override
    public void createActions() {
        createActionRecord();
        createActionCancel();
    }

    @Override
    public void configure() {
        createActions();
        setVisible(true);
    }

    @Override
    public void register(ObserverJInternalFrame o) {
        observerJInternalFrames.add(o);
    }

    @Override
    public void updateObserversWasFinalized() {
        observerJInternalFrames.stream().forEach((observerJInternalFrame) -> {
            observerJInternalFrame.wasFinalized(this);
        });
    }

    @Override
    public void updateViews(String msg) {
        if (msg != null) {
            JOptionPane.showMessageDialog(this, msg);
            return;
        }
        updateViewFromModel();
    }

    @Override
    public void errorOcurred(String error) {
        if (error == null) {
            JOptionPane.showMessageDialog(this, "um erro desconhecido ocorreu");
        } else {
            JOptionPane.showMessageDialog(this, error);
        }
    }
    @Override
    public void updateModelFromViewValues() {
        loginModel.setName(jFormattedTextFieldName.getText());
        loginModel.setLogin(jFormattedTextFieldLogin.getText());
        loginModel.setSenha(jPasswordFieldSenha.getText());
    }

}
