/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.uem.iss.petshop.ServiceOrder.view;

import br.com.uem.iss.petshop.Interfaces.ObserverJInternalFrame;
import br.com.uem.iss.petshop.Interfaces.ObserverModel;
import br.com.uem.iss.petshop.Interfaces.ViewInterface;
import br.com.uem.iss.petshop.ServiceOrder.controller.ServiceOrderController;
import br.com.uem.iss.petshop.ServiceOrder.model.ServiceOrderModel;
import br.com.uem.iss.petshop.Utils.DateUtil;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author EDUARDO
 */
public class ServiceOrderView extends javax.swing.JInternalFrame 
                              implements ViewInterface, 
                                         ServiceOrderModel.ObserverServiceOrderChangeAnimal,
                                         ServiceOrderModel.ObserverServiceOrderChangeCustomer,
                                         ServiceOrderModel.ObserverServiceOrderAdded,
                                         ServiceOrderModel.ObserverServiceOrderRemoved, 
                                         ServiceOrderModel.ObserverTotalCalculed{

    /**
     * Creates new form ServiceOrderView
     */
    /*
    public ServiceOrderView() {
        initComponents();
    }
    */
    final private ServiceOrderController serviceOrderController;
    final private ServiceOrderModel serviceOrderModel;
    final private ArrayList<ObserverJInternalFrame> oberverJInternalFrames;
    public ServiceOrderView(ServiceOrderController c, ServiceOrderModel m) {
        initComponents();
        serviceOrderController = c;
        serviceOrderModel = m;
        oberverJInternalFrames = new ArrayList<>();
        registerObservers();
        updateViewFromModel();
        
    }
    
    public void enableTextFields() {
        enableTextFields(true);
    }
    
    public void disableTextFields() {
        enableTextFields(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSelectCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCustomerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCustomerLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCustomerPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCustomerBirth = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonSelectAnimal = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldAnimalName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldAnimalBirth = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableServiceOrders = new javax.swing.JTable();
        jButtonAddService = new javax.swing.JButton();
        jButtonRemoveService = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonCancel = new javax.swing.JButton();
        jButtonRecord = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldExecuteDate = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaNote = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxPaymentType = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldEntryValue = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxServiceOrderStatus = new javax.swing.JComboBox();
        jTextFieldVendor = new javax.swing.JTextField();
        jButtonCloseServiceOrder = new javax.swing.JButton();

        setMaximizable(true);
        setResizable(true);
        setTitle("Ordem de Serviço");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Cliente"));

        jButtonSelectCustomer.setText("Selecionar Cliente...");

        jLabel1.setText("Nome:");

        jTextFieldCustomerName.setText("jTextField1");

        jLabel2.setText("Sobrenome:");

        jTextFieldCustomerLastName.setText("jTextField2");

        jLabel3.setText("Telefone:");

        jTextFieldCustomerPhone.setText("jTextField3");

        jLabel5.setText("Dt.Nasc:");

        jTextFieldCustomerBirth.setText("jTextField4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonSelectCustomer)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCustomerPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCustomerLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jTextFieldCustomerBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButtonSelectCustomer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCustomerName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCustomerPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCustomerBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldCustomerLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Do Animal"));

        jButtonSelectAnimal.setText("Selecionar Animal...");

        jLabel4.setText("Nome:");

        jTextFieldAnimalName.setText("jTextField5");

        jLabel6.setText("Dt.Nasc:");

        jTextFieldAnimalBirth.setText("jTextField6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldAnimalBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnimalName, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 163, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonSelectAnimal)
                .addGap(230, 230, 230))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonSelectAnimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAnimalName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAnimalBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços"));
        jPanel4.setToolTipText("");

        jTableServiceOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableServiceOrders);

        jButtonAddService.setText("Acicionar Servico");

        jButtonRemoveService.setText("Remover Servico");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total:");

        jTextFieldTotal.setText("jTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonAddService)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonRemoveService)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddService)
                    .addComponent(jButtonRemoveService))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonCancel.setText("Cancelar");

        jButtonRecord.setText("Gravar");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da Ordem de Serviço"));

        jLabel8.setText("Data de execução:");

        jTextFieldExecuteDate.setText("jTextField1");

        jLabel9.setText("Observações:");

        jTextAreaNote.setColumns(20);
        jTextAreaNote.setRows(5);
        jScrollPane2.setViewportView(jTextAreaNote);

        jLabel10.setText("Vendedor:");

        jLabel11.setText("Tipo de Pagamento:");

        jComboBoxPaymentType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Valor da entrada:");

        jTextFieldEntryValue.setText("jTextField2");

        jLabel13.setText("Situação da Ordem de Servico:");

        jComboBoxServiceOrderStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextFieldVendor.setText("jTextField3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldExecuteDate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addGap(38, 38, 38)
                                .addComponent(jTextFieldVendor, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxServiceOrderStatus, 0, 205, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTextFieldEntryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxPaymentType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldExecuteDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldVendor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jComboBoxServiceOrderStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxPaymentType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEntryValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonCloseServiceOrder.setText("Fechar Ordem de Servico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCloseServiceOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRecord))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonRecord)
                    .addComponent(jButtonCloseServiceOrder))
                .addGap(6, 6, 6))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel1, jPanel3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddService;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCloseServiceOrder;
    private javax.swing.JButton jButtonRecord;
    private javax.swing.JButton jButtonRemoveService;
    private javax.swing.JButton jButtonSelectAnimal;
    private javax.swing.JButton jButtonSelectCustomer;
    private javax.swing.JComboBox jComboBoxPaymentType;
    private javax.swing.JComboBox jComboBoxServiceOrderStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServiceOrders;
    private javax.swing.JTextArea jTextAreaNote;
    private javax.swing.JTextField jTextFieldAnimalBirth;
    private javax.swing.JTextField jTextFieldAnimalName;
    private javax.swing.JTextField jTextFieldCustomerBirth;
    private javax.swing.JTextField jTextFieldCustomerLastName;
    private javax.swing.JTextField jTextFieldCustomerName;
    private javax.swing.JTextField jTextFieldCustomerPhone;
    private javax.swing.JTextField jTextFieldEntryValue;
    private javax.swing.JTextField jTextFieldExecuteDate;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldVendor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void createActions() {
        createRecordAction();
        createCancelAction();
        createSelectCustomerAction();
        createSelectAnimalAction();
        createAddServiceAction();
        createRemoveServiceAction();
        createCloseServiceOrderAction();
        //TODO: Criar acoes
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void configure() {
        createActions();
        setVisible(true);
    }

    @Override
    public void updateModelFromViewValues() {
        
    }

    @Override
    public void updateViewFromModel() {
        dynamicFillComponents();
        updateViewCustomerData();
        updateViewAnimalData();
        updateViewServiceOrderData();
        refreshTableService();
    }

    @Override
    public void register(ObserverJInternalFrame o) {
        oberverJInternalFrames.add(o);
    }

    @Override
    public void updateObserversWasFinalized() {
        for (ObserverJInternalFrame observerJInternalFrame : oberverJInternalFrames) {
            observerJInternalFrame.wasFinalized(this);
        }
    }

    @Override
    public void updateViews(String msg) {
        if (msg != null) {
            JOptionPane.showMessageDialog(this, msg);
            return;
        }
        updateViewFromModel();
    }

    private void finalizeServiceOrderView() {
        updateObserversWasFinalized();
        dispose();
    }

    @Override
    public void errorOcurred(String error) {
        if (error != null) {
            JOptionPane.showMessageDialog(this, error);
        } else {
            JOptionPane.showMessageDialog(this, "um erro desconhecido ocorreu");
        }
    }

    private void createRecordAction() {
        jButtonRecord.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                recordAction();
            }
        });
    }
    
    private void recordAction(){
        DateUtil dateUtil = new DateUtil();
        if (!dateUtil.isValid(jTextFieldExecuteDate.getText())){
            JOptionPane.showMessageDialog(this, "Data inválida!","Informação", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (jTextFieldEntryValue.getText().contains(",")){
            JOptionPane.showMessageDialog(this, "O campo Valor da entrada deve utilizar ponto(.) como separador!", "Mensagem do sistema", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
        serviceOrderModel.setPaymentTypeByIndex(jComboBoxPaymentType.getSelectedIndex());
        serviceOrderModel.setStatuByIndex(jComboBoxServiceOrderStatus.getSelectedIndex());
        serviceOrderModel.setNote(jTextAreaNote.getText());
        serviceOrderModel.setVendor(jTextFieldVendor.getText());
        serviceOrderModel.setExecuteDate(dateUtil.toDate(jTextFieldExecuteDate.getText()));
        try {
            serviceOrderModel.setEntryValue(new Double(jTextFieldEntryValue.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao converter o campo de entrada", "Erro do sistema", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!serviceOrderController.persist()){
            return;
        }
        
        finalizeServiceOrderView();
    }
    
    private void createCancelAction() {
        jButtonCancel.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                cancelAction();
            }
        });
    }
    
    private void cancelAction(){
        finalizeServiceOrderView();
    }

    private void updateViewCustomerData() {
        jTextFieldCustomerName.setText(serviceOrderModel.getCustomerName());
        jTextFieldCustomerLastName.setText(serviceOrderModel.getCustomerLastName());
        jTextFieldCustomerPhone.setText(serviceOrderModel.getCustomerPhone());
        jTextFieldCustomerBirth.setText(serviceOrderModel.getCustomerBirth());
        
    }

    private void updateViewAnimalData() {
        jTextFieldAnimalName.setText(serviceOrderModel.getAnimalName());
        jTextFieldAnimalBirth.setText(serviceOrderModel.getAnimalBirth());
    }

    @Override
    public void animalChanged() {
        updateViewAnimalData();
    }

    @Override
    public void customerChanged() {
        updateViewCustomerData();
        jButtonSelectAnimal.setEnabled(true);
    }

    private void createSelectCustomerAction() {
        jButtonSelectCustomer.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                selectCustomerAction();
            }
        });
    }

    private void selectCustomerAction(){
        serviceOrderController.selectCustomer();
    }
    
    private void createSelectAnimalAction() {
        jButtonSelectAnimal.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                selectAnimalAction();
            }
        });
    }
    
    private void selectAnimalAction(){
        serviceOrderController.selectAnimal();
        
    }

    private void enableTextFields(Boolean enable){
        jTextFieldAnimalBirth.setEditable(enable);
        jTextFieldAnimalName.setEditable(enable);
        jTextFieldCustomerBirth.setEditable(enable);
        jTextFieldCustomerLastName.setEditable(enable);
        jTextFieldCustomerName.setEditable(enable);
        jTextFieldCustomerPhone.setEditable(enable);
        jTextFieldTotal.setEditable(enable);
    }

    private void createAddServiceAction() {
        jButtonAddService.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                addServiceAction();
            }
        });
    }

    private void addServiceAction() {
        serviceOrderController.addService();
    }
    
    private void createRemoveServiceAction() {
        jButtonRemoveService.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                removeServiceAction();
            }
        });
    }
    
    private void removeServiceAction() {
        if (jTableServiceOrders.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Nenhum serviço selecionado!", "Informação", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        serviceOrderController.removeService(jTableServiceOrders.getSelectedRow());
    }

    private void registerObservers() {
        serviceOrderModel.registerErrorObserver((ObserverModel)this);
        serviceOrderModel.registerUpdate((ObserverModel)this);
        serviceOrderModel.register((ServiceOrderModel.ObserverServiceOrderChangeAnimal)this);
        serviceOrderModel.register((ServiceOrderModel.ObserverServiceOrderChangeCustomer)this);
        serviceOrderModel.register((ServiceOrderModel.ObserverServiceOrderAdded)this);
        serviceOrderModel.register((ServiceOrderModel.ObserverServiceOrderRemoved)this);
        serviceOrderModel.register((ServiceOrderModel.ObserverTotalCalculed)this);
    }

    @Override
    public void addedService() {
        refreshTableService();
    }

    @Override
    public void removedService() {
        refreshTableService();
    }

    private void refreshTableService() {
        jTableServiceOrders.setModel(serviceOrderModel.createServiceModel());
        jTableServiceOrders.revalidate();
        jTableServiceOrders.clearSelection();
        calculeTotal();
    }

    public void enableInsertMode() {
        jButtonSelectCustomer.setEnabled(true);
        jButtonSelectAnimal.setEnabled(false);
        jButtonAddService.setEnabled(true);
        jButtonRemoveService.setEnabled(true);
    }

    public void enableEditMode() {
        enableInsertMode();
        jButtonSelectCustomer.setEnabled(false);
        jButtonSelectAnimal.setEnabled(false);
    }

    private void calculeTotal() {
        serviceOrderController.calculeTotal();
    }

    @Override
    public void totalWasCalculed(BigDecimal value) {
        jTextFieldTotal.setText(value.toString());
    }

    public void disableAllControls() {
        jTextAreaNote.setEditable(false);
        jTextFieldEntryValue.setEditable(false);
        jTextFieldExecuteDate.setEditable(false);
        jTextFieldVendor.setEditable(false);
        jButtonAddService.setEnabled(false);
        jButtonCloseServiceOrder.setEnabled(false);
        jButtonRecord.setEnabled(false);
        jButtonRemoveService.setEnabled(false);
    }

    private void createCloseServiceOrderAction() {
        jButtonCloseServiceOrder.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                closeServiceOrderAction();
            }
        });
    }
    
    private void closeServiceOrderAction() {
        throw new UnsupportedOperationException();
    }

    private void updateViewServiceOrderData() {
        DateUtil dateUtil = new DateUtil();
        jTextFieldExecuteDate.setText(dateUtil.toString(serviceOrderModel.getExecuteDate()));
        jTextFieldEntryValue.setText(serviceOrderModel.getEntryValue());
        jTextFieldVendor.setText(serviceOrderModel.getVendor());
        jTextAreaNote.setText(serviceOrderModel.getNote());
        jComboBoxServiceOrderStatus.setSelectedIndex(serviceOrderModel.getStatusIndex());
        jComboBoxPaymentType.setSelectedIndex(serviceOrderModel.getPaymentIndex());
    }

    private void dynamicFillComponents() {
        
        jComboBoxPaymentType.removeAllItems();
        for (Object object : serviceOrderModel.getPaymentSituations()) {
            jComboBoxPaymentType.addItem(object);
        }
        
        jComboBoxServiceOrderStatus.removeAllItems();
        for (Object object : serviceOrderModel.getStausSituation()) {
            jComboBoxServiceOrderStatus.addItem(object);
        }
    }
}
